Remove `spring-watcher-listen` and bump `spring` version
This resolves errors like:

```
bin/rails generate dockerfile --sudo
/Users/christophernady/.rvm/gems/ruby-3.1.2/gems/spring-2.1.1/lib/spring/application.rb:103:in `block in preload': undefined method `mechanism=' for ActiveSupport::Dependencies:Module

        ActiveSupport::Dependencies.mechanism = :load
                                   ^^^^^^^^^^^^ (NoMethodError)
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/christophernady/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /Users/christophernady/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/christophernady/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/christophernady/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/christophernady/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /Users/christophernady/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /Users/christophernady/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/christophernady/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /Users/christophernady/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
	from /Users/christophernady/Development/code/katy-hiking-trails/config/environment.rb:5:in `<top (required)>'
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/spring-2.1.1/lib/spring/application.rb:106:in `preload'
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from <internal:/Users/christophernady/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/christophernady/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from -e:1:in `<main>'
```

I found this solution on stack overflow here:
https://stackoverflow.com/questions/70849954/undefined-method-mechanism-for-activesupportdependenciesmodule-nomethoder.