Remove `deploy` section from `fly.toml`
From https://community.fly.io/t/no-machines-in-group-app-launching-one-new-machine-error-error-creating-a-new-machine-failed-to-launch-vm-to-create-more-than-1-machine-per-app-please-add-a-payment-method/12592/6:

> Do you have a release_command value set in the [deploy] section of your fly.toml? That will try to create a temporary, extra, Machine to run the command you specify.

Removing this section from the `fly.toml` file allows the deployment to succeed.

Before:

```
fly deploy --ha=false
==> Verifying app config
Validating /Users/christophernady/Development/code/katy-hiking-trails/fly.toml
Platform: machines
✓ Configuration is valid
--> Verified app config
==> Building image
Remote builder fly-builder-morning-star-3620 ready
==> Building image with Docker
--> docker host: 20.10.12 linux x86_64
[+] Building 0.7s (22/22) FINISHED
 => [internal] load build definition from Dockerfile                                                  0.0s
 => => transferring dockerfile: 32B                                                                   0.0s
 => [internal] load .dockerignore                                                                     0.0s
 => => transferring context: 35B                                                                      0.0s
 => resolve image config for docker.io/docker/dockerfile:experimental                                 0.2s
 => CACHED docker-image://docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850b  0.0s
 => [internal] load metadata for quay.io/evl.ms/fullstaq-ruby:3.1.2-jemalloc-slim                     0.2s
 => [base 1/4] FROM quay.io/evl.ms/fullstaq-ruby:3.1.2-jemalloc-slim@sha256:6a18708ef1cbc3dfa8c14a1f  0.0s
 => [internal] load build context                                                                     0.1s
 => => transferring context: 18.16kB                                                                  0.1s
 => CACHED [base 2/4] RUN mkdir /app                                                                  0.0s
 => CACHED [base 3/4] WORKDIR /app                                                                    0.0s
 => CACHED [base 4/4] RUN mkdir -p tmp/pids                                                           0.0s
 => CACHED [stage-3 1/7] RUN --mount=type=cache,id=prod-apt-cache,sharing=locked,target=/var/cache/a  0.0s
 => CACHED [build_deps 1/1] RUN --mount=type=cache,id=dev-apt-cache,sharing=locked,target=/var/cache  0.0s
 => CACHED [gems 1/3] RUN gem update --system --no-document &&     gem install -N bundler -v 2.3.7    0.0s
 => CACHED [gems 2/3] COPY Gemfile* ./                                                                0.0s
 => CACHED [gems 3/3] RUN bundle install &&  rm -rf vendor/bundle/ruby/*/cache                        0.0s
 => CACHED [stage-3 2/7] COPY --from=gems /app /app                                                   0.0s
 => CACHED [stage-3 3/7] COPY --from=gems /usr/lib/fullstaq-ruby/versions /usr/lib/fullstaq-ruby/ver  0.0s
 => CACHED [stage-3 4/7] COPY --from=gems /usr/local/bundle /usr/local/bundle                         0.0s
 => CACHED [stage-3 5/7] COPY . .                                                                     0.0s
 => CACHED [stage-3 6/7] RUN chmod +x /app/bin/* &&     sed -i 's/ruby.exe/ruby/' /app/bin/* &&       0.0s
 => CACHED [stage-3 7/7] RUN bin/rails fly:build                                                      0.0s
 => exporting to image                                                                                0.0s
 => => exporting layers                                                                               0.0s
 => => writing image sha256:942995cf0f0f8decbb3e5ed73e79123b4885c2f3da1b2b43b031f91a9bbe2476          0.0s
 => => naming to registry.fly.io/katy-hiking-trails:deployment-01HBMN946WZY1RKDATEWWYFDV8             0.0s
--> Building image done
==> Pushing image to fly
The push refers to repository [registry.fly.io/katy-hiking-trails]
244006513f42: Layer already exists
0734fe7c70c9: Layer already exists
9ec274835f95: Layer already exists
08464b2ef8a6: Layer already exists
7b8f1f64742d: Layer already exists
b66b5b56888d: Layer already exists
9ca8774e57e9: Layer already exists
7a0bbd64612f: Layer already exists
5f70bf18a086: Layer already exists
bee8f269f0a6: Layer already exists
50f407b42369: Layer already exists
a12586ed027f: Layer already exists
deployment-01HBMN946WZY1RKDATEWWYFDV8: digest: sha256:2782bc6f10bd6cf3876e3ee1a35c9c3ec43695d3924b2bbe19e5155d08f48e71 size: 2836
--> Pushing image done
image: registry.fly.io/katy-hiking-trails:deployment-01HBMN946WZY1RKDATEWWYFDV8
image size: 531 MB

Watch your deployment at https://fly.io/apps/katy-hiking-trails/monitoring

Running katy-hiking-trails release_command: bin/rails fly:release

-------
 ✔ release_command 5683900a73138e completed successfully
-------
This deployment will:
 * create 1 "app" machine

No machines in group app, launching a new machine

-------
 ✖ Failed: error creating a new machine: failed to launch VM: To create more than 1 machine per app plea…
-------
Error: error creating a new machine: failed to launch VM: To create more than 1 machine per app please add a payment method. https://fly.io/dashboard/christopher-nady/billing
Please note that release commands run in their own ephemeral machine, and therefore count towards the machine limit. (Request ID: 01HBMN9KTQY7KG0XS61KFAT78S-dfw)
```

After:

```
fly deploy --ha=false
==> Verifying app config
Validating /Users/christophernady/Development/code/katy-hiking-trails/fly.toml
Platform: machines
✓ Configuration is valid
--> Verified app config
==> Building image
Remote builder fly-builder-morning-star-3620 ready
==> Building image with Docker
--> docker host: 20.10.12 linux x86_64
[+] Building 8.6s (22/22) FINISHED
 => [internal] load build definition from Dockerfile                                                  0.0s
 => => transferring dockerfile: 32B                                                                   0.0s
 => [internal] load .dockerignore                                                                     0.0s
 => => transferring context: 35B                                                                      0.0s
 => resolve image config for docker.io/docker/dockerfile:experimental                                 1.1s
 => CACHED docker-image://docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850b  0.0s
 => [internal] load metadata for quay.io/evl.ms/fullstaq-ruby:3.1.2-jemalloc-slim                     0.2s
 => [base 1/4] FROM quay.io/evl.ms/fullstaq-ruby:3.1.2-jemalloc-slim@sha256:6a18708ef1cbc3dfa8c14a1f  0.0s
 => [internal] load build context                                                                     0.1s
 => => transferring context: 21.42kB                                                                  0.1s
 => CACHED [base 2/4] RUN mkdir /app                                                                  0.0s
 => CACHED [base 3/4] WORKDIR /app                                                                    0.0s
 => CACHED [base 4/4] RUN mkdir -p tmp/pids                                                           0.0s
 => CACHED [stage-3 1/7] RUN --mount=type=cache,id=prod-apt-cache,sharing=locked,target=/var/cache/a  0.0s
 => CACHED [build_deps 1/1] RUN --mount=type=cache,id=dev-apt-cache,sharing=locked,target=/var/cache  0.0s
 => CACHED [gems 1/3] RUN gem update --system --no-document &&     gem install -N bundler -v 2.3.7    0.0s
 => CACHED [gems 2/3] COPY Gemfile* ./                                                                0.0s
 => CACHED [gems 3/3] RUN bundle install &&  rm -rf vendor/bundle/ruby/*/cache                        0.0s
 => CACHED [stage-3 2/7] COPY --from=gems /app /app                                                   0.0s
 => CACHED [stage-3 3/7] COPY --from=gems /usr/lib/fullstaq-ruby/versions /usr/lib/fullstaq-ruby/ver  0.0s
 => CACHED [stage-3 4/7] COPY --from=gems /usr/local/bundle /usr/local/bundle                         0.0s
 => [stage-3 5/7] COPY . .                                                                            0.0s
 => [stage-3 6/7] RUN chmod +x /app/bin/* &&     sed -i 's/ruby.exe/ruby/' /app/bin/* &&     sed -i   0.2s
 => [stage-3 7/7] RUN bin/rails fly:build                                                             6.8s
 => exporting to image                                                                                0.1s
 => => exporting layers                                                                               0.1s
 => => writing image sha256:91ed96a3a53540259cb792ee69e347f1cb5ac4518ada67d9b94a0b92a3597d9d          0.0s
 => => naming to registry.fly.io/katy-hiking-trails:deployment-01HBMNDQ7HJZTF5FNTKZ44E88N             0.0s
--> Building image done
==> Pushing image to fly
The push refers to repository [registry.fly.io/katy-hiking-trails]
386797891702: Pushed
d400c1f157c6: Pushed
d911358c4af7: Pushed
08464b2ef8a6: Layer already exists
7b8f1f64742d: Layer already exists
b66b5b56888d: Layer already exists
9ca8774e57e9: Layer already exists
7a0bbd64612f: Layer already exists
5f70bf18a086: Layer already exists
bee8f269f0a6: Layer already exists
50f407b42369: Layer already exists
a12586ed027f: Layer already exists
deployment-01HBMNDQ7HJZTF5FNTKZ44E88N: digest: sha256:10076e8c4de4d0835df5148b73e6711e0c3bd61517628c66655e5e33324ffdf2 size: 2836
--> Pushing image done
image: registry.fly.io/katy-hiking-trails:deployment-01HBMNDQ7HJZTF5FNTKZ44E88N
image size: 531 MB

Watch your deployment at https://fly.io/apps/katy-hiking-trails/monitoring

This deployment will:
 * create 1 "app" machine

No machines in group app, launching a new machine
Finished launching new machines

Visit your newly deployed app at https://katy-hiking-trails.fly.dev/
```